language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8"
  - "6"
script: npm test
after_success:
  - npm run coverage:report
  - npm run travis-deploy-once "npm run semantic-release"
notifications:
  email:
    on_success: never
